spring:
  application:
    name: authentication
    description: This service contains all the API for the management, registration and authentication of users.
    version: @project.version@
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://isc:4RKsJQfuvvuG@localhost:8888/}
    spring:
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
          ddl-auto: update
        show-sql: 'false'
      datasource:
        testWhileIdle: 'true'
        password: root
        username: root
        url: jdbc:mysql://localhost:3306/isc?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        validationQuery: SELECT 1
      servlet:
        multipart:
          max-file-size: 100MB
          max-request-size: 100MB
      mvc:
        view:
          prefix: /
          suffix: .jsp
